import React, { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { api } from '../services/api';
import {
  Sparkles,
  Bot,
  BookOpen,
  HelpCircle,
  Award,
  CheckCircle2,
  AlertCircle,
  Copy,
  Check,
  Send,
  ArrowRight,
} from 'lucide-react';

export const AiEducationalToolsView: React.FC = () => {
  const { currentTenant, showToast } = useAuth();
  const [activeSubTab, setActiveSubTab] = useState<'evaluator' | 'lesson-plan' | 'quiz-gen'>('evaluator');

  // Tool 1: Fluency Evaluator State
  const [studentText, setStudentText] = useState(
    'In recent years, the amount of pollution in big cities is increasing very much. Many people thinks that government should to ban private cars from downtown area, while other people believe that public transport is not good enough yet.'
  );
  const [examType, setExamType] = useState('IELTS Academic Writing Task 2');
  const [targetBand, setTargetBand] = useState('7.5');
  const [evaluating, setEvaluating] = useState(false);
  const [evaluationResult, setEvaluationResult] = useState<any>(null);

  // Tool 2: Lesson Plan Generator State
  const [lessonTopic, setLessonTopic] = useState('Second Conditionals in Business Negotiations & Hypotheticals');
  const [lessonLevel, setLessonLevel] = useState('B2');
  const [lessonDuration, setLessonDuration] = useState(60);
  const [lessonFocus, setLessonFocus] = useState('Communicative Fluency & Meaning-Form-Pronunciation (MFP)');
  const [generatingPlan, setGeneratingPlan] = useState(false);
  const [planResult, setPlanResult] = useState<string | null>(null);
  const [copiedPlan, setCopiedPlan] = useState(false);

  // Tool 3: Quiz Generator State
  const [quizTopic, setQuizTopic] = useState('Past Perfect vs Past Simple in Narrative Tenses');
  const [quizLevel, setQuizLevel] = useState('B1');
  const [quizCount, setQuizCount] = useState(3);
  const [generatingQuiz, setGeneratingQuiz] = useState(false);
  const [generatedQuestions, setGeneratedQuestions] = useState<any[]>([]);

  // Handlers
  const handleEvaluate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!studentText.trim() || studentText.length < 15) {
      showToast('Please enter at least 15 characters of text to evaluate', 'error');
      return;
    }

    try {
      setEvaluating(true);
      setEvaluationResult(null);
      const res = await api.evaluateFluency({
        studentText,
        examType,
        targetBand,
      });

      if (res.success) {
        setEvaluationResult(res.evaluation);
        showToast('Fluency evaluation generated by Gemini!', 'success');
      }
    } catch (err: any) {
      showToast(err.message || 'Evaluation failed', 'error');
    } finally {
      setEvaluating(false);
    }
  };

  const handleGeneratePlan = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!lessonTopic.trim()) {
      showToast('Please enter a lesson topic', 'error');
      return;
    }

    try {
      setGeneratingPlan(true);
      setPlanResult(null);
      const res = await api.generateLessonPlan({
        topic: lessonTopic,
        level: lessonLevel,
        durationMinutes: lessonDuration,
        focusArea: lessonFocus,
      });

      if (res.success) {
        setPlanResult(res.plan);
        showToast('CELTA lesson plan generated successfully!', 'success');
      }
    } catch (err: any) {
      showToast(err.message || 'Failed to generate plan', 'error');
    } finally {
      setGeneratingPlan(false);
    }
  };

  const handleGenerateQuiz = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      setGeneratingQuiz(true);
      setGeneratedQuestions([]);
      const res = await api.generateQuiz({
        topic: quizTopic,
        level: quizLevel,
        count: quizCount,
      });

      if (res.success) {
        setGeneratedQuestions(res.questions);
        showToast(`Generated ${res.questions.length} quiz questions!`, 'success');
      }
    } catch (err: any) {
      showToast(err.message || 'Failed to generate quiz', 'error');
    } finally {
      setGeneratingQuiz(false);
    }
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedPlan(true);
    setTimeout(() => setCopiedPlan(false), 2000);
    showToast('Lesson plan copied to clipboard!', 'info');
  };

  return (
    <div className="space-y-6">
      {/* Header Banner */}
      <div className="bg-gradient-to-r from-indigo-950 via-slate-900 to-indigo-900 text-white rounded-2xl p-6 shadow-md border border-indigo-900/50 flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-500/20 border border-indigo-400/30 text-indigo-200 text-xs font-semibold mb-2">
            <Sparkles className="w-3.5 h-3.5 text-amber-300" />
            <span>Server-Side Gemini 3.8-Flash Educational AI Studio</span>
          </div>
          <h1 className="text-2xl font-extrabold tracking-tight">
            AI Pedagogical Intelligence Suite
          </h1>
          <p className="text-xs text-slate-300 mt-1 max-w-2xl">
            Custom-prompted for English language acquisition, CEFR diagnostics, and teacher planning.
            All AI queries run strictly server-side with tenant credit tracking.
          </p>
        </div>

        <div className="flex flex-col items-end text-xs text-slate-300">
          <span className="font-semibold text-white">
            {currentTenant?.aiCreditsUsed || 1420} / {currentTenant?.aiCreditsLimit || 5000} Credits
          </span>
          <span className="text-[11px] text-indigo-300">Tenant: {currentTenant?.name}</span>
        </div>
      </div>

      {/* Sub-tab Navigation */}
      <div className="flex flex-wrap gap-2 border-b border-slate-200 pb-3">
        <button
          onClick={() => setActiveSubTab('evaluator')}
          className={`px-4 py-2 rounded-xl text-xs font-semibold transition flex items-center gap-2 ${
            activeSubTab === 'evaluator'
              ? 'bg-indigo-600 text-white shadow-sm'
              : 'bg-white border border-slate-200 text-slate-700 hover:bg-slate-50'
          }`}
        >
          <Bot className="w-4 h-4" />
          <span>IELTS & Fluency Evaluator</span>
        </button>

        <button
          onClick={() => setActiveSubTab('lesson-plan')}
          className={`px-4 py-2 rounded-xl text-xs font-semibold transition flex items-center gap-2 ${
            activeSubTab === 'lesson-plan'
              ? 'bg-indigo-600 text-white shadow-sm'
              : 'bg-white border border-slate-200 text-slate-700 hover:bg-slate-50'
          }`}
        >
          <BookOpen className="w-4 h-4" />
          <span>CELTA Lesson Plan Generator</span>
        </button>

        <button
          onClick={() => setActiveSubTab('quiz-gen')}
          className={`px-4 py-2 rounded-xl text-xs font-semibold transition flex items-center gap-2 ${
            activeSubTab === 'quiz-gen'
              ? 'bg-indigo-600 text-white shadow-sm'
              : 'bg-white border border-slate-200 text-slate-700 hover:bg-slate-50'
          }`}
        >
          <HelpCircle className="w-4 h-4" />
          <span>Automated Quiz Authoring</span>
        </button>
      </div>

      {/* Tool 1: Fluency Evaluator */}
      {activeSubTab === 'evaluator' && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Input form */}
          <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm space-y-4">
            <div>
              <h3 className="text-sm font-bold text-slate-900">
                Student Text / Speech Transcript
              </h3>
              <p className="text-xs text-slate-500 mt-0.5">
                Paste student writing or audio transcript for immediate linguistic analysis.
              </p>
            </div>

            <form onSubmit={handleEvaluate} className="space-y-4 text-xs">
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="font-semibold text-slate-700 block mb-1">
                    Assessment Benchmark
                  </label>
                  <select
                    value={examType}
                    onChange={(e) => setExamType(e.target.value)}
                    className="w-full p-2.5 rounded-xl border border-slate-200 bg-white"
                  >
                    <option value="IELTS Academic Writing Task 2">IELTS Academic Task 2</option>
                    <option value="IELTS General Writing Task 1">IELTS General Task 1</option>
                    <option value="CEFR Spoken Fluency Diagnostic">CEFR Spoken Fluency</option>
                    <option value="Cambridge C1 Advanced">Cambridge C1 Advanced</option>
                  </select>
                </div>

                <div>
                  <label className="font-semibold text-slate-700 block mb-1">
                    Target Band / Level
                  </label>
                  <select
                    value={targetBand}
                    onChange={(e) => setTargetBand(e.target.value)}
                    className="w-full p-2.5 rounded-xl border border-slate-200 bg-white"
                  >
                    <option value="6.5">Band 6.5 (Competent / B2)</option>
                    <option value="7.0">Band 7.0 (Good / B2-C1)</option>
                    <option value="7.5">Band 7.5 (Very Good / C1)</option>
                    <option value="8.0">Band 8.0 (Advanced / C1-C2)</option>
                    <option value="8.5">Band 8.5 (Expert / C2)</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="font-semibold text-slate-700 block mb-1">
                  Student Submission Content
                </label>
                <textarea
                  rows={8}
                  value={studentText}
                  onChange={(e) => setStudentText(e.target.value)}
                  placeholder="Paste essay text or speaking transcript..."
                  className="w-full p-3 rounded-xl border border-slate-200 bg-slate-50 text-slate-800 focus:outline-none focus:ring-2 focus:ring-indigo-500 font-sans leading-relaxed"
                />
              </div>

              <button
                type="submit"
                disabled={evaluating}
                className="w-full py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-semibold flex items-center justify-center gap-2 shadow-sm transition disabled:opacity-50"
              >
                <Sparkles className="w-4 h-4 text-amber-300" />
                <span>{evaluating ? 'Analyzing with Gemini...' : 'Run Deep Linguistic Assessment'}</span>
              </button>
            </form>
          </div>

          {/* Results display */}
          <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm space-y-4">
            <h3 className="text-sm font-bold text-slate-900 border-b border-slate-100 pb-3">
              Diagnostic Assessment Report
            </h3>

            {evaluating ? (
              <div className="p-12 text-center text-xs text-slate-500 space-y-2">
                <div className="w-8 h-8 rounded-full border-2 border-indigo-600 border-t-transparent animate-spin mx-auto"></div>
                <p>Gemini is parsing lexical collocations and grammatical accuracy...</p>
              </div>
            ) : evaluationResult ? (
              <div className="space-y-4 text-xs animate-in fade-in">
                <div className="flex items-center justify-between p-4 rounded-xl bg-indigo-50/80 border border-indigo-100">
                  <div>
                    <span className="text-[10px] uppercase font-bold text-indigo-700 tracking-wider">
                      Estimated Band / CEFR
                    </span>
                    <h4 className="text-2xl font-black text-indigo-950 mt-0.5">
                      Band {evaluationResult.estimatedBand}
                    </h4>
                  </div>
                  <span className="text-xs bg-white text-indigo-700 font-bold px-3 py-1 rounded-lg border border-indigo-200 shadow-sm">
                    {evaluationResult.cefrEquivalent || 'B2+ Upper Intermediate'}
                  </span>
                </div>

                {/* Criterion breakdown */}
                <div className="space-y-2">
                  <h5 className="font-bold text-slate-800 text-xs">Criteria Analysis:</h5>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-[11px]">
                    <div className="p-2.5 rounded-lg bg-slate-50 border border-slate-200">
                      <span className="font-bold text-slate-700 block">Grammatical Range:</span>
                      <p className="text-slate-600 mt-0.5">{evaluationResult.grammarAccuracy}</p>
                    </div>
                    <div className="p-2.5 rounded-lg bg-slate-50 border border-slate-200">
                      <span className="font-bold text-slate-700 block">Lexical Resource:</span>
                      <p className="text-slate-600 mt-0.5">{evaluationResult.lexicalResource}</p>
                    </div>
                    <div className="p-2.5 rounded-lg bg-slate-50 border border-slate-200 sm:col-span-2">
                      <span className="font-bold text-slate-700 block">Coherence & Structure:</span>
                      <p className="text-slate-600 mt-0.5">{evaluationResult.coherenceCohesion}</p>
                    </div>
                  </div>
                </div>

                {/* Grammatical Errors Table */}
                {evaluationResult.grammarErrors && evaluationResult.grammarErrors.length > 0 && (
                  <div>
                    <h5 className="font-bold text-slate-800 text-xs mb-1.5">
                      Identified Errors & Targeted Corrections:
                    </h5>
                    <div className="space-y-2">
                      {evaluationResult.grammarErrors.map((err: any, idx: number) => (
                        <div
                          key={idx}
                          className="p-2.5 rounded-lg bg-rose-50/50 border border-rose-100 text-[11px] space-y-1"
                        >
                          <div className="flex items-center gap-2">
                            <span className="text-rose-700 line-through font-mono">
                              "{err.original}"
                            </span>
                            <ArrowRight className="w-3 h-3 text-slate-400" />
                            <span className="text-emerald-700 font-bold font-mono">
                              "{err.correction}"
                            </span>
                          </div>
                          <p className="text-slate-600 text-[10px]">{err.explanation}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Vocabulary Upgrades */}
                {evaluationResult.suggestedVocabularyUpgrades &&
                  evaluationResult.suggestedVocabularyUpgrades.length > 0 && (
                    <div>
                      <h5 className="font-bold text-slate-800 text-xs mb-1.5">
                        High-Band Lexical Upgrades:
                      </h5>
                      <div className="space-y-1.5">
                        {evaluationResult.suggestedVocabularyUpgrades.map(
                          (upg: any, idx: number) => (
                            <div
                              key={idx}
                              className="p-2 rounded-lg bg-emerald-50/60 border border-emerald-100 text-[11px] flex items-center justify-between"
                            >
                              <div>
                                <span className="text-slate-500 font-mono">
                                  "{upg.basicWord}" →{' '}
                                </span>
                                <strong className="text-emerald-800 font-mono">
                                  "{upg.advancedAlternative}"
                                </strong>
                              </div>
                              <span className="text-[10px] text-slate-500 italic max-w-xs truncate">
                                {upg.context}
                              </span>
                            </div>
                          )
                        )}
                      </div>
                    </div>
                  )}
              </div>
            ) : (
              <div className="p-12 text-center text-xs text-slate-400">
                Submit a student essay or transcription to generate an instant diagnostic report.
              </div>
            )}
          </div>
        </div>
      )}

      {/* Tool 2: Lesson Plan Generator */}
      {activeSubTab === 'lesson-plan' && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm space-y-4">
            <h3 className="text-sm font-bold text-slate-900">Lesson Parameters</h3>
            <form onSubmit={handleGeneratePlan} className="space-y-4 text-xs">
              <div>
                <label className="font-semibold text-slate-700 block mb-1">
                  Target Topic & Communicative Goal *
                </label>
                <input
                  type="text"
                  required
                  value={lessonTopic}
                  onChange={(e) => setLessonTopic(e.target.value)}
                  placeholder="e.g. Expressing Disagreement Politely in Boardroom Settings"
                  className="w-full p-2.5 rounded-xl border border-slate-200 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="font-semibold text-slate-700 block mb-1">CEFR Level</label>
                  <select
                    value={lessonLevel}
                    onChange={(e) => setLessonLevel(e.target.value)}
                    className="w-full p-2.5 rounded-xl border border-slate-200 bg-white"
                  >
                    <option value="A1">A1 - Starter</option>
                    <option value="A2">A2 - Elementary</option>
                    <option value="B1">B1 - Intermediate</option>
                    <option value="B2">B2 - Upper Intermediate</option>
                    <option value="C1">C1 - Advanced</option>
                  </select>
                </div>

                <div>
                  <label className="font-semibold text-slate-700 block mb-1">Duration</label>
                  <select
                    value={lessonDuration}
                    onChange={(e) => setLessonDuration(Number(e.target.value))}
                    className="w-full p-2.5 rounded-xl border border-slate-200 bg-white"
                  >
                    <option value={45}>45 Minutes</option>
                    <option value={60}>60 Minutes</option>
                    <option value={90}>90 Minutes</option>
                    <option value={120}>120 Minutes</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="font-semibold text-slate-700 block mb-1">Pedagogical Focus</label>
                <input
                  type="text"
                  value={lessonFocus}
                  onChange={(e) => setLessonFocus(e.target.value)}
                  placeholder="e.g. Spoken Fluency, MFP, IELTS Speaking Part 3"
                  className="w-full p-2.5 rounded-xl border border-slate-200"
                />
              </div>

              <button
                type="submit"
                disabled={generatingPlan}
                className="w-full py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-semibold flex items-center justify-center gap-2 shadow-sm transition disabled:opacity-50"
              >
                <Sparkles className="w-4 h-4 text-amber-300" />
                <span>
                  {generatingPlan ? 'Generating Lesson Plan...' : 'Generate CELTA Lesson Plan'}
                </span>
              </button>
            </form>
          </div>

          <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm space-y-4">
            <div className="flex items-center justify-between border-b border-slate-100 pb-3">
              <h3 className="text-sm font-bold text-slate-900">Generated Lesson Framework</h3>
              {planResult && (
                <button
                  onClick={() => copyToClipboard(planResult)}
                  className="px-3 py-1 rounded-lg border border-slate-200 hover:bg-slate-50 text-xs text-slate-600 flex items-center gap-1.5 transition"
                >
                  {copiedPlan ? (
                    <Check className="w-3.5 h-3.5 text-emerald-600" />
                  ) : (
                    <Copy className="w-3.5 h-3.5" />
                  )}
                  <span>{copiedPlan ? 'Copied' : 'Copy'}</span>
                </button>
              )}
            </div>

            {generatingPlan ? (
              <div className="p-12 text-center text-xs text-slate-500 space-y-2">
                <div className="w-8 h-8 rounded-full border-2 border-indigo-600 border-t-transparent animate-spin mx-auto"></div>
                <p>Synthesizing stage aims, timing, and controlled practice tasks...</p>
              </div>
            ) : planResult ? (
              <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 text-xs text-slate-800 whitespace-pre-wrap font-sans leading-relaxed max-h-[500px] overflow-y-auto">
                {planResult}
              </div>
            ) : (
              <div className="p-12 text-center text-xs text-slate-400">
                Configure lesson goals and generate a full CELTA/DELTA staged plan.
              </div>
            )}
          </div>
        </div>
      )}

      {/* Tool 3: Quiz Generator */}
      {activeSubTab === 'quiz-gen' && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm space-y-4">
            <h3 className="text-sm font-bold text-slate-900">Quiz Generator Config</h3>
            <form onSubmit={handleGenerateQuiz} className="space-y-4 text-xs">
              <div>
                <label className="font-semibold text-slate-700 block mb-1">Target Topic *</label>
                <input
                  type="text"
                  required
                  value={quizTopic}
                  onChange={(e) => setQuizTopic(e.target.value)}
                  placeholder="e.g. Reported Speech, Phrasal Verbs with 'Take'"
                  className="w-full p-2.5 rounded-xl border border-slate-200"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="font-semibold text-slate-700 block mb-1">CEFR Level</label>
                  <select
                    value={quizLevel}
                    onChange={(e) => setQuizLevel(e.target.value)}
                    className="w-full p-2.5 rounded-xl border border-slate-200 bg-white"
                  >
                    <option value="A2">A2 - Elementary</option>
                    <option value="B1">B1 - Intermediate</option>
                    <option value="B2">B2 - Upper Intermediate</option>
                    <option value="C1">C1 - Advanced</option>
                  </select>
                </div>

                <div>
                  <label className="font-semibold text-slate-700 block mb-1">
                    Number of Questions
                  </label>
                  <select
                    value={quizCount}
                    onChange={(e) => setQuizCount(Number(e.target.value))}
                    className="w-full p-2.5 rounded-xl border border-slate-200 bg-white"
                  >
                    <option value={2}>2 Questions</option>
                    <option value={3}>3 Questions</option>
                    <option value={5}>5 Questions</option>
                  </select>
                </div>
              </div>

              <button
                type="submit"
                disabled={generatingQuiz}
                className="w-full py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-semibold flex items-center justify-center gap-2 shadow-sm transition disabled:opacity-50"
              >
                <Sparkles className="w-4 h-4 text-amber-300" />
                <span>
                  {generatingQuiz ? 'Generating Questions...' : 'Generate Exam Questions'}
                </span>
              </button>
            </form>
          </div>

          <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm space-y-4">
            <h3 className="text-sm font-bold text-slate-900 border-b border-slate-100 pb-3">
              Generated Questions
            </h3>

            {generatingQuiz ? (
              <div className="p-12 text-center text-xs text-slate-500 space-y-2">
                <div className="w-8 h-8 rounded-full border-2 border-indigo-600 border-t-transparent animate-spin mx-auto"></div>
                <p>Generating multiple-choice distractors and pedagogical rationale...</p>
              </div>
            ) : generatedQuestions.length > 0 ? (
              <div className="space-y-4 text-xs">
                {generatedQuestions.map((q, idx) => (
                  <div key={idx} className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-2">
                    <p className="font-bold text-slate-900">
                      {idx + 1}. {q.question}
                    </p>
                    <div className="space-y-1">
                      {q.options.map((opt: string, optIdx: number) => (
                        <div
                          key={optIdx}
                          className={`p-2 rounded-lg border text-[11px] ${
                            optIdx === q.correctOptionIndex
                              ? 'bg-emerald-50 border-emerald-300 text-emerald-900 font-bold'
                              : 'bg-white border-slate-200 text-slate-600'
                          }`}
                        >
                          {opt} {optIdx === q.correctOptionIndex && '✓ (Correct)'}
                        </div>
                      ))}
                    </div>
                    <p className="text-[10px] text-slate-500 italic mt-1">
                      <strong>Rationale:</strong> {q.explanation}
                    </p>
                  </div>
                ))}
              </div>
            ) : (
              <div className="p-12 text-center text-xs text-slate-400">
                Click generate to draft automated grammar & vocabulary questions.
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};
